services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
  worker:
    build:
      context: .
      dockerfile: Dockerfile.local
  seamoon-gateway:
    build:
      context: .
      dockerfile: Dockerfile.local

  ymicp:
    build:
      context: .
      dockerfile: Dockerfile.ymicp
