FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY . ./
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/seamoon-core ./cmd/seamoon-core

FROM scratch
WORKDIR /app
COPY --from=build /out/seamoon-core /app/seamoon-core
EXPOSE 9000
ENTRYPOINT ["/app/seamoon-core"]
CMD ["server", "-p", "9000", "-t", "websocket"]
